# Generated by Django 6.0.3 on 2026-04-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodstock',
            old_name='quantity',
            new_name='units',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='bank',
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='city',
            field=models.CharField(default='Delhi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='contact',
            field=models.CharField(default='Delhi', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='hospital_name',
            field=models.CharField(default='Unknown Hospital', max_length=100),
            preserve_default=False,
        ),
    ]
