# Generated by Django 6.0.3 on 2026-04-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_quantity_bloodstock_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='city',
            field=models.CharField(default='AB+', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='contact',
            field=models.CharField(default='AB+', max_length=15),
            preserve_default=False,
        ),
    ]
